//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiskOfCoins.Resources.Text {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class popups {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal popups() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RiskOfCoins.Resources.Text.popups", typeof(popups).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to load the latest backup?
        ///This might make your game profiles work again if they broke for some reason, but it will also undo anything you&apos;ve done in the game after the last time you applied lunar coins..
        /// </summary>
        internal static string askBackupLoad {
            get {
                return ResourceManager.GetString("askBackupLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string askConfirmationCaption {
            get {
                return ResourceManager.GetString("askConfirmationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Forbidden.
        /// </summary>
        internal static string errorAccessForbiddenCaption {
            get {
                return ResourceManager.GetString("errorAccessForbiddenCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find any profiles in path:
        ///{{0}}.
        /// </summary>
        internal static string errorBackupNoProfiles {
            get {
                return ResourceManager.GetString("errorBackupNoProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed profile copy due to a system I/O issue.
        ///
        ///From:
        ///{{0}}
        ///To:
        ///{{1}}
        ///{{2}}.
        /// </summary>
        internal static string errorBackupProfileCopyIO {
            get {
                return ResourceManager.GetString("errorBackupProfileCopyIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied while trying to copy profiles.
        ///
        ///From:
        ///{{0}}
        ///To:
        ///{{1}}.
        /// </summary>
        internal static string errorBackupProfileCopyUnauthorized {
            get {
                return ResourceManager.GetString("errorBackupProfileCopyUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied while trying to modify profile:
        ///{{0}}.
        /// </summary>
        internal static string errorCoinWriteIO {
            get {
                return ResourceManager.GetString("errorCoinWriteIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile modification failed due to a system I/O issue:
        ///{{0}}
        ///
        ///{{1}}.
        /// </summary>
        internal static string errorCoinWriteUnauthorized {
            get {
                return ResourceManager.GetString("errorCoinWriteUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles backup wasn&apos;t fully successful, so no action will be taken..
        /// </summary>
        internal static string errorFullBackup {
            get {
                return ResourceManager.GetString("errorFullBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunar coins amount must be a positive integer up to {{0}}.
        /// </summary>
        internal static string errorInvalidLunarCoins {
            get {
                return ResourceManager.GetString("errorInvalidLunarCoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Operation.
        /// </summary>
        internal static string errorInvalidOperationCaption {
            get {
                return ResourceManager.GetString("errorInvalidOperationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a valid Steam folder!.
        /// </summary>
        internal static string errorInvalidSteamPath {
            get {
                return ResourceManager.GetString("errorInvalidSteamPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Steam Path.
        /// </summary>
        internal static string errorInvalidSteamPathCaption {
            get {
                return ResourceManager.GetString("errorInvalidSteamPathCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User ID.
        /// </summary>
        internal static string errorInvalidUserIdCaption {
            get {
                return ResourceManager.GetString("errorInvalidUserIdCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I/O Error.
        /// </summary>
        internal static string errorIOCaption {
            get {
                return ResourceManager.GetString("errorIOCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find any profiles to apply coins to..
        /// </summary>
        internal static string errorNoProfilesToBackup {
            get {
                return ResourceManager.GetString("errorNoProfilesToBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find any profiles to load backups of..
        /// </summary>
        internal static string errorNoProfilesToLoad {
            get {
                return ResourceManager.GetString("errorNoProfilesToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Aborted.
        /// </summary>
        internal static string errorOperationAbortedCaption {
            get {
                return ResourceManager.GetString("errorOperationAbortedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problems During Revertion.
        /// </summary>
        internal static string errorProblemsDuringRevertionCaption {
            get {
                return ResourceManager.GetString("errorProblemsDuringRevertionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Serialization Error&quot;.
        /// </summary>
        internal static string errorSerializationCaption {
            get {
                return ResourceManager.GetString("errorSerializationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t load previous application data. Consider deleting the .RoC file.
        /// </summary>
        internal static string errorSerializationLoad {
            get {
                return ResourceManager.GetString("errorSerializationLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t save current application data.
        /// </summary>
        internal static string errorSerializationSave {
            get {
                return ResourceManager.GetString("errorSerializationSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected Steam path isn&apos;t a folder or doesn&apos;t exist!.
        /// </summary>
        internal static string errorSteamPathWasInvalid {
            get {
                return ResourceManager.GetString("errorSteamPathWasInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Steam Path.
        /// </summary>
        internal static string errorSteamPathWasInvalidCaption {
            get {
                return ResourceManager.GetString("errorSteamPathWasInvalidCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Exception.
        /// </summary>
        internal static string errorUnexpectedExceptionCaption {
            get {
                return ResourceManager.GetString("errorUnexpectedExceptionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user wasn&apos;t valid. Try it again!.
        /// </summary>
        internal static string errorUserWasInvalid {
            get {
                return ResourceManager.GetString("errorUserWasInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t load the following profile backups:
        ///{{0}}.
        /// </summary>
        internal static string infoBackupLoadFailedList {
            get {
                return ResourceManager.GetString("infoBackupLoadFailedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following profile backups were loaded:
        ///{{0}}.
        /// </summary>
        internal static string infoBackupLoadLoadedList {
            get {
                return ResourceManager.GetString("infoBackupLoadLoadedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t backup the following profiles:
        ///{{0}}.
        /// </summary>
        internal static string infoBackupSaveFailedList {
            get {
                return ResourceManager.GetString("infoBackupSaveFailedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A backup has been performed for the following profiles:
        ///{{0}}.
        /// </summary>
        internal static string infoBackupSaveSavedList {
            get {
                return ResourceManager.GetString("infoBackupSaveSavedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t modify the following profiles:
        ///{{0}}.
        /// </summary>
        internal static string infoCoinWriteFailedList {
            get {
                return ResourceManager.GetString("infoCoinWriteFailedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified profiles:
        ///{{0}}.
        /// </summary>
        internal static string infoCoinWriteWrittenList {
            get {
                return ResourceManager.GetString("infoCoinWriteWrittenList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverted Profiles.
        /// </summary>
        internal static string infoRevertedProfilesCaption {
            get {
                return ResourceManager.GetString("infoRevertedProfilesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Finished.
        /// </summary>
        internal static string infoTaskFinishedCaption {
            get {
                return ResourceManager.GetString("infoTaskFinishedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Value.
        /// </summary>
        internal static string invalidValueCaption {
            get {
                return ResourceManager.GetString("invalidValueCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles backup succeeded. Will try to apply coins..
        /// </summary>
        internal static string successFullBackup {
            get {
                return ResourceManager.GetString("successFullBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam Path updated..
        /// </summary>
        internal static string successSteamPath {
            get {
                return ResourceManager.GetString("successSteamPath", resourceCulture);
            }
        }
    }
}
