//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiskOfCoins.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class popups {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal popups() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RiskOfCoins.Resources.popups", typeof(popups).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Couldn&apos;t find any profiles in path:
        ///{{0}}.
        /// </summary>
        internal static string errorBackupNoProfiles {
            get {
                return ResourceManager.GetString("errorBackupNoProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed profile copy due to a system I/O issue.
        ///
        ///From:
        ///{{0}}
        ///To:
        ///{{1}}
        ///{{2}}.
        /// </summary>
        internal static string errorBackupProfileCopyIO {
            get {
                return ResourceManager.GetString("errorBackupProfileCopyIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Access denied while trying to copy profiles.
        ///
        ///From:
        ///{{0}}
        ///To:
        ///{{1}}.
        /// </summary>
        internal static string errorBackupProfileCopyUnauthorized {
            get {
                return ResourceManager.GetString("errorBackupProfileCopyUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Access denied while trying to modify profile:
        ///{{0}}.
        /// </summary>
        internal static string errorCoinWriteIO {
            get {
                return ResourceManager.GetString("errorCoinWriteIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile modification failed due to a system I/O issue:
        ///{{0}}
        ///
        ///{{1}}.
        /// </summary>
        internal static string errorCoinWriteUnauthorized {
            get {
                return ResourceManager.GetString("errorCoinWriteUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lunar coins amount must be a positive integer up to {{0}}.
        /// </summary>
        internal static string errorInvalidLunarCoins {
            get {
                return ResourceManager.GetString("errorInvalidLunarCoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must select a valid Steam folder!.
        /// </summary>
        internal static string errorInvalidSteamPath {
            get {
                return ResourceManager.GetString("errorInvalidSteamPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid Steam Path.
        /// </summary>
        internal static string errorInvalidSteamPathCaption {
            get {
                return ResourceManager.GetString("errorInvalidSteamPathCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Couldn&apos;t load previous application data. Consider deleting the .RoC file.
        /// </summary>
        internal static string errorSerializationLoad {
            get {
                return ResourceManager.GetString("errorSerializationLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Couldn&apos;t save current application data.
        /// </summary>
        internal static string errorSerializationSave {
            get {
                return ResourceManager.GetString("errorSerializationSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The selected Steam path isn&apos;t a folder or doesn&apos;t exist!.
        /// </summary>
        internal static string errorSteamPathWasInvalid {
            get {
                return ResourceManager.GetString("errorSteamPathWasInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user wasn&apos;t valid. Try it again!.
        /// </summary>
        internal static string errorUserWasInvalid {
            get {
                return ResourceManager.GetString("errorUserWasInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Couldn&apos;t load the following profile backups:
        ///{{0}}.
        /// </summary>
        internal static string infoBackupLoadFailedList {
            get {
                return ResourceManager.GetString("infoBackupLoadFailedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The following profile backups were loaded:
        ///{{0}}.
        /// </summary>
        internal static string infoBackupLoadLoadedList {
            get {
                return ResourceManager.GetString("infoBackupLoadLoadedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Couldn&apos;t backup the following profiles:
        ///{{0}}.
        /// </summary>
        internal static string infoBackupSaveFailedList {
            get {
                return ResourceManager.GetString("infoBackupSaveFailedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A backup has been performed for the following profiles:
        ///{{0}}.
        /// </summary>
        internal static string infoBackupSaveSavedList {
            get {
                return ResourceManager.GetString("infoBackupSaveSavedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Couldn&apos;t modify the following profiles:
        ///{{0}}.
        /// </summary>
        internal static string infoCoinWriteFailedList {
            get {
                return ResourceManager.GetString("infoCoinWriteFailedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modified profiles:
        ///{{0}}.
        /// </summary>
        internal static string infoCoinWriteWrittenList {
            get {
                return ResourceManager.GetString("infoCoinWriteWrittenList", resourceCulture);
            }
        }
    }
}
